---
#name of the jobs scenario
name: Checks

#trigger
on: [push]

#add jobs
jobs: 
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      #first step: login to dockerhubhub
      - name: Login to Docker Hub
        #builtin action in github
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN}}
      #github ation to check the code inside github/actions job and use it
      #there are jobs wher you dont need access to the code 
      - name: Checkout
        uses: actions/checkout@v2
      #RUN command for TEST
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      #RUN command for LINTING
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"